[project]
name = "odoo-addons-oca-ddmrp"
version = "19.0.20260617.1"
dependencies = [
    "odoo-addon-ddmrp==19.0.*",
    "odoo-addon-ddmrp_adjustment==19.0.*",
    "odoo-addon-ddmrp_history==19.0.*",
    "odoo-addon-ddmrp_warning==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
